version: "3.8"

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: raquelanddavi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: raquelanddavi_db
      MYSQL_USER: raquelanddavi_user
      MYSQL_PASSWORD: raquelanddavi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - raquelanddavi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Aplicação Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raquelanddavi-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://raquelanddavi_user:raquelanddavi_password@mysql:3306/raquelanddavi_db
      - NODE_ENV=production
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - raquelanddavi-network
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx (opcional - para proxy reverso)
  nginx:
    image: nginx:alpine
    container_name: raquelanddavi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - raquelanddavi-network

volumes:
  mysql_data:

networks:
  raquelanddavi-network:
    driver: bridge
